baseURL = "https://glittering-scone-1a840e.netlify.app"

languageCode = "en-us"
title = "Photographies de Tom"
theme = "PaperMod"

[params]
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  noindex = true
